import express from "express";
import cors from "cors";
import nodemailer from "nodemailer";
import dotenv from "dotenv";
dotenv.config();

const app = express();

app.use(
  cors({
    origin: [
      "http://localhost:5173",
      "https://gaurav-developer-portfolio.vercel.app",
    ],
    methods: ["POST"],
  })
);

app.use(express.json());

// Gmail transporter
const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
});

// Contact Route
app.post("/api/contact", async (req, res) => {
  const { name, email, subject, message } = req.body;
  if (!name || !email || !message)
    return res
      .status(400)
      .json({ success: false, message: "All fields required." });

  try {
    await transporter.sendMail({
      from: `"${name}" <${process.env.EMAIL_USER}>`,
      to: process.env.RECEIVER_EMAIL,
      replyTo: email,
      subject: subject || "New Contact Message",
      html: `
        <div style="background:#f4f6f8; padding:32px 0; font-family:'Segoe UI',Roboto,Helvetica,Arial,sans-serif; color:#111827;">
  <div style="max-width:640px; margin:auto; background:#ffffff; border-radius:12px; overflow:hidden; box-shadow:0 6px 18px rgba(0,0,0,0.08);">
    
    <!-- Header -->
    <div style="background:linear-gradient(135deg,#2563eb,#1d4ed8); padding:20px 32px; text-align:center; color:#ffffff;">
      <h1 style="margin:0; font-size:22px; font-weight:600;">New Contact Form Message</h1>
    </div>

    <!-- Body -->
    <div style="padding:28px 32px; line-height:1.6;">
      <p style="margin:0 0 12px;">Hello <strong>Gaurav</strong>,</p>
      <p style="margin:0 0 24px;">You’ve received a new message from your portfolio contact form:</p>

      <table cellpadding="6" cellspacing="0" style="width:100%; border-collapse:collapse; font-size:15px;">
        <tr>
          <td style="width:120px; color:#6b7280; font-weight:600;">Name:</td>
          <td style="color:#111827;">${name}</td>
        </tr>
        <tr>
          <td style="color:#6b7280; font-weight:600;">Email:</td>
          <td><a href="mailto:${email}" style="color:#2563eb; text-decoration:none;">${email}</a></td>
        </tr>
        <tr>
          <td style="color:#6b7280; font-weight:600;">Subject:</td>
          <td>${subject || "(No subject)"}</td>
        </tr>
      </table>

      <div style="margin-top:24px;">
        <p style="margin-bottom:8px; color:#6b7280; font-weight:600;">Message:</p>
        <div style="background:#f9fafb; border-left:4px solid #2563eb; padding:16px; border-radius:8px; font-size:15px; color:#111827; white-space:pre-line;">
          ${message}
        </div>
      </div>
    </div>

    <!-- Footer -->
    <div style="background:#f9fafb; text-align:center; padding:16px; font-size:13px; color:#6b7280; border-top:1px solid #e5e7eb;">
      <p style="margin:4px 0;">© ${new Date().getFullYear()} Gaurav Portfolio System</p>
      <p style="margin:4px 0;">This message was automatically generated by your contact form.</p>
    </div>
  </div>
</div>

      `,
    });

    res
      .status(200)
      .json({ success: true, message: "Email sent successfully!" });
  } catch (err) {
    console.error("Email send error:", err);
    res.status(500).json({ success: false, message: "Failed to send email." });
  }
});

const PORT = process.env.PORT || 8285;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
